### ISSUE TITLE
Define exporting interface

### ISSUE THREAD

**Issue by dazuma** [census-instrumentation/opencensus-ruby#16]
There isn't yet an interface to initiate the exporting process. It may make sense to put this on SpanContext, and have corresponding wrappers at the Trace level. There also needs to be an exporter configuration added to the config module so applications can define which exporter(s) to use.

**Comment by chingor13** [comment]
All you need is the list of spans. I would advocate for exporter interface to be a single method:

```ruby
##
# @param [Array<Span>] spans
# @return [Boolean]
#
def export(spans); end
```

Perhaps add a method `SpanContext#spans_for_export` which would transform the accumulated `SpanBuilder` instances to `Span`s.

**Comment by dazuma** [comment]
Agreed, but I think there are two pieces. One, as you say, a `SpanContext#spans_for_export` method, and second, something that invokes configured exporters on the resulting built spans.

**Comment by chingor13** [comment]
If a middleware framework is available, I'd expect something like:

```ruby
class Middleware
  def initialize app, exporter: nil
    @app = app
    @exporter ||= OpenCensus::Trace::Config.exporter
  end

  def call env
    OpenCensus::Trace.start_request_trace rack_env: env do |span_context|
      begin
        @app.call env
      ensure
        @exporter.export span_context.spans_for_export if @exporter
      end
    end
  end
end
```

If there's not a middleware framework, I'd expect the developer to have to do 3 things:
1. Instantiate the exporter from configuration
2. Start a request trace (`OpenCensus::Trace.start_request_trace`) and capture the root span context object.
3. After processing the request, call exporter.exporter on the root span context
