### ISSUE TITLE
Write Stackdriver Exporter

### ISSUE THREAD

**Issue by chingor13** [census-instrumentation/opencensus-ruby#25]
Rename Google Cloud -> Stackdriver

**Comment by dazuma** [comment]
I wonder if this exporter should live in the `google-cloud-trace` library. So neither `google-cloud-trace` nor `opencensus` should have a hard dependency on the other, but if both are present then the stackdriver exporter is available.

**Comment by chingor13** [comment]
We could put this in a separate gem like `opencensus-stackdriver` which would have dependencies on `opencensus` and `google-cloud-trace`. That way neither `opencensus` nor `google-cloud-trace` have an explicit dependency on each other.

We could do something similar for other exporters as well.

**Comment by chingor13** [comment]
We'll split the exporters out into their own libraries. This one will be in `opencensus-stackdriver` but will provide the exporter as `OpenCensus::Trace::Exporters::StackdriverExporter` (and `OpenCensus::Stats::Exporters::StackdriverExporter` when stats is implemented.

**Comment by dazuma** [comment]
This will be done in https://github.com/census-instrumentation/ruby-stackdriver-exporter
