### ISSUE TITLE
Write Zipkin Exporter

### ISSUE THREAD

**Issue by chingor13** [census-instrumentation/opencensus-ruby#26]

**Comment by dazuma** [comment]
We'll split the exporters out into their own libraries. This one will be in `opencensus-zipkin` but will provide the exporter as `OpenCensus::Trace::Exporters::ZipkinExporter` (and `OpenCensus::Stats::Exporters::ZipkinExporter` when stats is implemented.)

**Comment by dazuma** [comment]
This will be done in https://github.com/census-instrumentation/ruby-zipkin-exporter
